module LLDB
  class LLDBError < StandardError
  end

  class InvalidObjectError < LLDBError
  end

  class LaunchError < LLDBError
  end

  class AttachError < LLDBError
  end

  class BreakpointError < LLDBError
  end

  class EvaluationError < LLDBError
  end

  class UnsupportedAPIError < LLDBError
  end

  class UnsupportedPlatformError < LLDBError
  end

  class IncompatibleWrapperError < LLDBError
  end
end
