module LLDB
  module StopReason
    PROCESSOR_TRACE: Integer
    FORK: Integer
    VFORK: Integer
    VFORK_DONE: Integer
  end

  module SymbolContextItem
    VARIABLE: Integer
  end

  module ValueType
    VARIABLE_THREAD_LOCAL: Integer
  end

  module ErrorType
    INVALID: Integer
    GENERIC: Integer
    MACH_KERNEL: Integer
    POSIX: Integer
    EXPRESSION: Integer
    WIN32: Integer
  end

  module ReturnStatus
    INVALID: Integer
    SUCCESS_FINISH_NO_RESULT: Integer
    SUCCESS_FINISH_RESULT: Integer
    SUCCESS_CONTINUING_NO_RESULT: Integer
    SUCCESS_CONTINUING_RESULT: Integer
    STARTED: Integer
    FAILED: Integer
    QUIT: Integer
  end

  module RunMode
    ONLY_THIS_THREAD: Integer
    ALL_THREADS: Integer
    ONLY_DURING_STEPPING: Integer
  end
end
